// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtwfSUFqd7HkdiZ7d2libRMCeqwH_tGfA',
    appId: '1:152884519603:web:9e2f40c6a21ed7938b46c6',
    messagingSenderId: '152884519603',
    projectId: 'notes-5d567',
    authDomain: 'notes-5d567.firebaseapp.com',
    storageBucket: 'notes-5d567.appspot.com',
    measurementId: 'G-903ZW9YD46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAszeKW9NV7DipFRFTj1p0fHwbLDocvfkE',
    appId: '1:152884519603:android:0bd51229a70ef84b8b46c6',
    messagingSenderId: '152884519603',
    projectId: 'notes-5d567',
    storageBucket: 'notes-5d567.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiYMt7U_dT7bGRHkUsGtOBxo_zOy24rGE',
    appId: '1:152884519603:ios:315d593dd7800eac8b46c6',
    messagingSenderId: '152884519603',
    projectId: 'notes-5d567',
    storageBucket: 'notes-5d567.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiYMt7U_dT7bGRHkUsGtOBxo_zOy24rGE',
    appId: '1:152884519603:ios:315d593dd7800eac8b46c6',
    messagingSenderId: '152884519603',
    projectId: 'notes-5d567',
    storageBucket: 'notes-5d567.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtwfSUFqd7HkdiZ7d2libRMCeqwH_tGfA',
    appId: '1:152884519603:web:b4c2b93bff0173c78b46c6',
    messagingSenderId: '152884519603',
    projectId: 'notes-5d567',
    authDomain: 'notes-5d567.firebaseapp.com',
    storageBucket: 'notes-5d567.appspot.com',
    measurementId: 'G-97P1LH5YZL',
  );
}
